[workspace]
members = [".", "babble-macros"]
default-members = [".", "babble-macros"]

[package]
name = "babble"
description = "improved library learning"
version = "0.1.0"
authors = ["David Cao <david@cao.sh>", "Rose Kunkel <rose@rosekunkel.me>"]
repository = "https://github.com/dcao/babble"
license = "MIT"
keywords = ["e-graphs", "program-synthesis"]
categories = ["command-line-utilities"]
edition = "2018"

[dependencies]
ahash = "0.7"
babble-macros = { path = "babble-macros" }
dashmap = "4.0"
egg = { git = "https://github.com/egraphs-good/egg", rev = "8d65a56" }
clap = "3.0.0-beta.2"
hashbrown = "0.11"
indexmap = "1.6"
itertools = "0.10"
ordered-float = "2.0"
env_logger = "0.7"
lazy_static = "1.4"
smallvec = { version = "1.6", features = ["union", "const_generics"] }

[dev-dependencies]
criterion = "0.3"

[lib]
name = "babble"
path = "src/lib.rs"

[[bin]]
name = "babble"
path = "src/main.rs"

[[bench]]
name = "babble_bench"
harness = false
