[package]
name = "babble"
description = "improved library learning"
version = "0.1.0"
authors = ["David Cao <david@cao.sh>", "Rose Kunkel <rose@rosekunkel.me>"]
repository = "https://github.com/dcao/babble"
license = "MIT"
keywords = ["e-graphs", "program-synthesis"]
categories = ["command-line-utilities"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
egg = "0.6"
indexmap = "1.6"
itertools = "0.10"
ordered-float = "2.0"
env_logger = "0.7"

[dev-dependencies]
criterion = "0.3"

[lib]
name = "babble"
path = "src/lib.rs"

[[bin]]
name = "babble"
path = "src/main.rs"

[[bench]]
name = "babble_bench"
harness = false
