[workspace]
members = [".", "babble-macros"]
default-members = [".", "babble-macros"]

[package]
name = "babble"
description = "improved library learning"
version = "0.1.0"
authors = ["David Cao <david@cao.sh>", "Rose Kunkel <rose@rosekunkel.me>"]
repository = "https://github.com/dcao/babble"
license = "MIT"
keywords = ["e-graphs", "program-synthesis"]
categories = ["command-line-utilities"]
edition = "2018"

[dependencies]
babble-macros = { path = "babble-macros" }
egg = { git = "https://github.com/egraphs-good/egg", rev = "ad1f088" }
clap = "3.0.0-beta.2"
indexmap = "1.6"
itertools = "0.10"
ordered-float = "2.0"
env_logger = "0.7"
lazy_static = "1.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
nom = "6"
thiserror = "1"
internment = { version = "0.5", features = ["arc"] }

[dev-dependencies]
criterion = "0.3"

[lib]
name = "babble"
path = "src/lib.rs"

[[bin]]
name = "babble"
path = "src/main.rs"

[[bench]]
name = "babble_bench"
harness = false

[profile.release]
debug = true
