[package]
name = "babble"
description = "improved library learning"
version = "0.1.0"
authors = ["David Cao <david@cao.sh>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
egg = "0.6"
ordered-float = "2.0"

[lib]
name = "babble"
path = "src/lib.rs"

[[bin]]
name = "babble"
path = "src/main.rs"
