name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '40 1 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build -v --workspace --tests
      - name: Run tests
        run: cargo test -v --workspace

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@clippy
      - run: cargo clippy -v --workspace --tests -- --deny warnings
